spring:
  application:
    name: provider
    #MQTT配置信息
  mqtt:
    #MQTT服务地址，端口号默认1883，如果有多个，用逗号隔开, 注意控制台的端口是18083,代码端口是1883
    url: tcp://106.14.142.184:1883
    #用户名
    username: admin
    #密码
    password: public
    #客户端id(不能重复)
    client:
      id: provider-id
    #MQTT默认的消息推送主题，实际可在调用接口是指定
    default:
      topic: topic
